### ISSUE TITLE
Some problems with saving back all changes to the files app and ideas how to solve it

### ISSUE THREAD

**Issue by szaimen** [ONLYOFFICE/onlyoffice-nextcloud#257] opened 2020-04-06 12:12 UTC
As discussed in https://github.com/nextcloud/documentserver_community/issues/12#issuecomment-609744050 downwards etc. there are a few problems with saving back the changes to the files app, which is not only related to the documentserver_community because currently the changes are only saved back to the files app, if no one has opened that file while a background job is performed which can lead to never saving the changes back to the files app. 

Here are my ideas how this problem could be reliably solved, you can see those ideas as additional ways to save back the changes.
1. always force a save if the last user that has the file open clicks on the close button. (needs a click action for that button to trigger a force save)
2. be able to trigger a force save to write back the changes to the files app when the shortcut "CTRL+S" is executed while the file is open
3. Maybe provide an additional "Save" button here: which would provide exactly the same functionality like the force save via shortcut: 
![image](https://user-images.githubusercontent.com/42591237/78556951-38719880-7810-11ea-860b-6852ebacf01a.png)

I know that not all changes can be made from your side but all functions need to get implemented in the connector first to be able to implement them on the documentserver side later on.

**Comment by putt1ck** [comment] 2020-08-28 06:40
This is a showstopper issue for deployment of OnlyOffice.  The trial kept hitting this issue; either people open a doc to make a quick client-requested final change, close it and then add it from NC as an attachment to an email (but the file hasn't got the changes yet), or they open a doc to make some requested edits and then tell people the doc is ready but haven't closed the browser tab.

A save button that actually, there and then, saves the file to the location it was opened from is the expected norm - anything different either has to be better (e.g. changes to the file are always saved to the location it was opened from) or it's seen as a major regression bug.

**Comment by acsfer** [comment] 2020-09-15 12:17
This is indeed a big problem; none of the files edited trough OnlyOffice are actually synced to our desktops because of this. this affects both DocumentServer embed in Nextcloud **and** this app with an DocumentServer dedicated instance.

@ibnpetr has asked for remote access to NC instance. I can provide it if needed.

**Comment by LinneyS** [comment] 2020-09-17 08:22
Hi @szaimen 
Try _Keep intermediate versions when editing_ in settings in v6.0.0

**Closed by LinneyS** 2020-09-17 08:22 UTC
Labels: forcesave

**Comment by putt1ck** [comment] 2020-09-17 09:14
@LinneyS will this solve the use case scenario for a normal user i.e. they open a document, make changes, close document; then immediately attach document to email from NC and send to client? Will that be the updated document or the one before they made the changes?

**Comment by acsfer** [comment] 2020-09-20 22:25
@LinneyS this option **does not solve this problem**.
File at Nextcloud still show a very old date after edit the file. (I've wait several minutes and refreshed the page several times).

**Comment by acsfer** [comment] 2020-09-20 22:30
@putt1ck no.

- Create a new Document file (empty)
- Edit it (put some text)
- Go back to Files app
- Wait 60sec and download it
- Open it locally
- **File is empty** (it has not been saved)
- Re-open file at Nextcloud for edition, changes are there...

**Comment by LinneyS** [comment] 2020-09-28 09:24
@putt1ck The final saving of the file is performed 10 seconds after the editors are closed by all co-editors.

**Comment by LinneyS** [comment] 2020-09-28 09:28
@acsfer It looks like the save is not being performed.
Saving the connection settings to ONLYOFFICE Document Server is successful? Create a new issue.

Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by putt1ck** [comment] 2020-09-28 09:58
@LinneyS that's a bug from a normal user's perspective. They expect to be able to save a file and have that mean it has changed on the storage they opened the file from. Is a button that forces save back to the storage not feasible in the architecture, something that calls the same process called 10 seconds after all the editor windows are closed?

**Comment by LinneyS** [comment] 2020-09-28 13:02
@putt1ck 
Saving and forcesave are different events. 
You can open issue [here](https://github.com/ONLYOFFICE/DocumentServer) with a description of the workflow from a normal user's perspective.
