### ISSUE TITLE
 Nextcloud 25.0.3 / OnlyOffice - Download instead of editing when sharing folder

### ISSUE THREAD

**Issue by CVZ-es** [ONLYOFFICE/onlyoffice-nextcloud#756] opened 2023-02-04 19:36 UTC
Hi everyone,

I recently migrated from Owncloud to Nextcloud.
I installed a new server from scratch for Nextcloud and Onlyoffice.
And I migrated my data from Owncloud to Nextcloud. according to the official documentation.
Both are running the latest version (25.0.3 for Nextcloud, and the latest docker image version for onlyoffice/documentserver).
And I'm running the lastest version of ONLYOFFICE	integration app: 7.6.8

When I share a file, and open it with a browser, I can succesfully edit file with Onlyoffice. So Onlyoffice is working fine.
When I share a folder, and open it with a browser, I can't edit files, and files get downloaded.

I disabled and uninstalled ONLYOFFICE app.
I flushed oc_appconfig table (delete from oc_appconfig where appid='onlyoffice';)
And reinstalled and reconfigured ONLYOFFICE app.

But I'm still facing the same problem.

So help is welcome!
Thanks in advance
Best
Damien
PS I'm Running Ubuntu 22.04 on each server,
PHP version is 8.1 on Nextcloud server

**Comment by CVZ-es** [comment] 2023-02-04 19:38
PS Same is happening with demo servers

**Comment by CVZ-es** [comment] 2023-02-04 19:58
I tried creating a new folder/ new shares, same problem.
Here are some test link
Direct link (working fine):
https://cloud.casadevelazquez.org/cloud/index.php/s/65rXXeH6tK6xH5g
Link to folder (downloading instead of editing)
https://cloud.casadevelazquez.org/cloud/index.php/s/goNNp5niokBEFBq

Best

**Comment by funktionierbar** [comment] 2023-02-08 10:21
Hi, I have the same problem (NC 25.0.3, Onlyoffice App 7.6.8). Will gladly provide logs if told what would be needed.
Onlyoffice is opened when I share a document, but not if I share a folder, and then the user opens the document in that folder, then a Download-Dialogue opens. 
greetings!

**Comment by Andragor** [comment] 2023-02-09 20:55
Hello, same Problem here. I'm running NC 25.0.3 and Onlyoffice 7.6.8. With NC 25.0.2 this problem wasn't there as far as I know.

**Comment by shoei101** [comment] 2023-02-10 19:37
Hello, just adding that we're having the same issue as the OP. Running NC 25.03 Onlyoffice NC App 7.6.8 and Onlyoffice Documentserver 7.3.0 (applied "the fix" stated here https://github.com/ONLYOFFICE/onlyoffice-nextcloud/commit/63b68953d807afc3397771507c210be006ed0330 but only works in Google Chrome half the time for us)

**Comment by shu0406** [comment] 2023-02-13 10:07
duplicate of https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/740 ?

**Comment by CVZ-es** [comment] 2023-02-18 10:14
Hi @shu0406
Yes, same, as #740
I've been waiting low production time (Saturday) to apply the fix, but unfortunately it doesn't work for us (I have tried both Google Chrome and Firefox)
Best

**Comment by shu0406** [comment] 2023-02-18 17:03
Looks like it is fixed already, just wait for the fix to be published.

**Comment by bseclier** [comment] 2023-02-21 09:15
Hello,
I'm facing the same problem here with Nextcloud 25.0.3 and the onlyoffice app 7.6.8.
The fix from #740 works well 90% of the time. It just doesn't work when we are logged to Nextcloud and try to access documents through the public link.

**Comment by shoei101** [comment] 2023-03-07 22:42
even with fix #740 applied, if you share a folder with a lot of documents (I have a shared folder with 23 documents) in it, to where you have to scroll down and open a document it only opens in half the screen. if I scroll back to the top of the shared folder I'm able to open document like normal

**Comment by michel-thomas** [comment] 2023-03-08 21:38
Fix in #757 works in my case (Nextcloud 25.0.4, OnlyOffice 7.6.8), whereas fix #740 does not. But I wonder when it will be released in onlyoffice app? Maybe @LinneyS could tell us? Many thanks for the patch!

**Comment by SergeyKorneyev** [comment] 2023-03-09 10:17
Hi @shoei101
Your particular scenario doesn't look like the one fixed by #740. Could you create a separate issue for this where you provide a more detailed description with screenshots?

**Closed** 2023-10-02 15:39 UTC
Labels: bug
