### ISSUE TITLE
Editing documents as guest in shared folders no longer possible (NC25)

### ISSUE THREAD

**Issue by arnowelzel** [ONLYOFFICE/onlyoffice-nextcloud#740] opened 2022-11-03 11:58 UTC
After updating to Nextcloud 25.0.0 it is no longer possible for guests to edit documents in shared folders with read/write access. If users click a document, it will only be offered to download but it will not be opened in the OnlyOffice document editor.

However, the same share works fine as soon as a user is logged in and no longer acts as a guest.

On the other hand when sharing individual documents, editing still works as expected.

So far I don't know if this is an issue with Nextcloud or with the integration app.

Server: Nextcloud 25.0.0 (also happens with 25.0.1)
OnlyOffice integration app: 7.6.8
OnlyOffice document server (Docker based): Community edition 7.10.215

**Comment by avvertix** [comment] 2022-11-08 13:48
This also happen to me after upgrading to NC 25

**Comment by awo-in-sachsen** [comment] 2022-11-08 22:11
This also happen to me toooo after upgrading to NC 25

**Comment by alvar-freude** [comment] 2022-11-10 12:31
Here is the same bug. I wonder if this is a bug in the Onlyoffice App or in Nextcloud. And, whether this occurs everywhere or only in certain configurations.

I guess, a fix should be easy, if someone knows where to look.
Unfortunately, the code is not self-explanatory or well documented, so I haven't found what the problem is yet.

**Comment by bruring** [comment] 2022-11-11 14:21
Same here, unfortunately. The OnlyOffice integration doesn't seem to register itself in the right way, it is possible to edit .txt files as a guest for example.

**Comment by arnowelzel** [comment] 2022-11-11 18:36
JFTR: the problem still exists after upgrading to NC 25.0.1.

**Comment by alvar-freude** [comment] 2022-11-13 02:09
> Same here, unfortunately. The OnlyOffice integration doesn't seem to register itself in the right way, it is possible to edit .txt files as a guest for example.

Hmmm … – I have no knowledge of Nextcloud app development; any idea, where to look or how the Onlyoffice app registersitself? 

**Workaround**

The bug seems to be related to the Files app. When using the direct link to edit a file, everything is fine, e.g.:

`https://mynextcloud/index.php/apps/onlyoffice/s/ShareToken?fileId=123`

Where `fileID` is the file ID, taken from the URL when editing as logged in user or sharing as internal link and `ShareToken` is from the share link.

So, if you give all URLs for all shared files to all participants, they can edit this files.

**Comment by szabogyula** [comment] 2022-11-18 08:12
This bug is a hard blocking issue to upgrade NC25 in our case. Is there any related issue in the [nextcloud issue tracker](https://github.com/nextcloud/server/issues) 🤔 ?

**Comment by arnowelzel** [comment] 2022-11-19 10:29
> > Same here, unfortunately. The OnlyOffice integration doesn't seem to register itself in the right way, it is possible to edit .txt files as a guest for example.
> 
> Hmmm … – I have no knowledge of Nextcloud app development; any idea, where to look or how the Onlyoffice app registers itself?
> 
> **Workaround**
> 
> The bug seems to be related to the Files app. When using the direct link to edit a file, everything is fine, e.g.:
> 
> `https://mynextcloud/index.php/apps/onlyoffice/s/ShareToken?fileId=123`
> 
> Where `fileID` is the file ID, taken from the URL when editing as logged in user or sharing as internal link and `ShareToken` is from the share link.
> 
> So, if you give all URLs for all shared files to all participants, they can edit this files.

The links as mentioned above is not correct. The change is as following:

Old - working in NC 24:

`https://server.example/s/<SOMESTRING>/?path=%2F&openfile=<ID>`

New - now only "download" in NC 25:

`https://server.example/s/<SOMESTRING>/download/?path=%2F&openfile=<ID>`

However using the old link format from NC24 does not work any longer in NC25. So maybe the app also has to do something to work in NC25 this way.

**Comment by FelixBuehler** [comment] 2022-11-22 10:48
Can confirm this issue after upgrading to NC25. Didn't change anything in OnlyOffice (in docker).

**Comment by mvvvmd** [comment] 2022-11-25 10:13
Tested the fix, seems to resolve the issue.

**Comment by pierresebastien** [comment] 2022-11-29 11:44
Hello,
I'm facing the same issue and I'm wondering when you plan to create a new release containing the fix https://github.com/ONLYOFFICE/onlyoffice-nextcloud/commit/63b68953d807afc3397771507c210be006ed0330 ? 
Best regards

**Comment by Setsaria** [comment] 2022-11-29 12:46
Hello
I've test the Fix, but It doesn't work.
I'm always stuck to download in shared folders

**Comment by mvvvmd** [comment] 2022-11-29 12:51
> Hello I've test the Fix, but It doesn't work. I'm always stuck to download in shared folders

I'm quite certain it does work, tested on two systems, perhaps you have a caching issue or some other variable is in play?

**Comment by Setsaria** [comment] 2022-11-29 12:56
I've tested on another servers.
It works with the last onlyoffice document server 7.2 and the last NC app 7.6.8

But it doesn't work with the onlyoffice-documentserver-ie          6.0.2-5 with the NC app 7.1.2.
I can't upgrade to 7.6.8 because it doesn't work with the onlyoffice-documentserver-ie          6.0.2-5 (it's the enterprise licence, and we don't have upgrade with this version)

**Comment by JMoVS** [comment] 2022-12-12 12:53
@Antipkin-A I tested it and your patch works but it hasn't been merged into main branch - when is the next release planned?

**Comment by taavit21** [comment] 2022-12-14 12:12
I had the exact same problem after upgrading NC25. That fix helped.
When can we expect to have a new version of onlyoffice available? I can only imagine we are not the only ones having this problem.

**Comment by JMoVS** [comment] 2022-12-14 12:14
@taavit21 If you feel comfortable with Git, you can deploy the branch that contains the fix now. Otherwise waiting for @Antipkin-A to make a release :)

**Comment by shu0406** [comment] 2022-12-21 08:15
Does v7.2.2 solve the problem?

Do I have to go to v7.2.2 once I update to NC25? Since it's seems that all previous versions (v7.2.1 and 7.1.X) contain the bug. I'd rather stay at our v7.1.2 since there are no major improvements in v7.2.X our clients would need.

**Comment by tomdereub** [comment] 2022-12-21 11:16
You can test it, but I think the problem is more with nextcloud's connector app than with onlyoffice version. The fix that's working is just modifying a conf file of nextcloud onlyoffice connector.
With onlyoffice 7.2.1.34 I still have the bug (and the fix works).

**Comment by kratzerph** [comment] 2023-01-26 14:49
We are faced with the problem too. Running the ubuntu nextcloud snap it's not possible to modify the conf files directly. Can you release a new version?

greets

**Comment by bseclier** [comment] 2023-02-21 09:14
Hello,
I'm facing the same problem here with Nextcloud 25.0.3 and the onlyoffice app 7.6.8.
Thank you @Antipkin-A for your workaround, it works well 90% of the time. It just doesn't work when we are logged to Nextcloud and try to access documents through the public link.

**Comment by ZID-TU-Graz** [comment] 2023-02-24 10:46
We are also affected. The fix works for us (thanks for the tip with the browser cache).

When can we expect a official release?

**Comment by tron65** [comment] 2023-02-24 11:09
yes, the fix works, it would be nice to have that indeed in an official release

**Comment by gentoolink** [comment] 2023-03-01 00:03
This fix worked well after clearing cache. Thanks

**Closed** 2023-03-20 10:44 UTC
Labels: bug

**Comment by m12cpl** [comment] 2023-08-28 07:57
I have a newest version of Nextcloud running and trying to use Whiteboard. But a user can't be a guest if she/he wants to edit the Whiteboard file. Is there a way to fix that?

**Comment by alvar-freude** [comment] 2023-09-19 14:05
With with Nextcloud 27.1. neither guests nor logged in users can edit Documents after clicking on the file. Instead the file will be downloaded. Tested with Version 8.2 and 8.1 of the Onlyoffice-App.

And in the app settings (log in ad admin) there is no list of  file types connected with onlyoffice.

**Comment by Mer0me** [comment] 2023-09-19 15:19
Nextcloud 27.1 and App 8.2 here, it works, I can edit .docx and .xlsx

**Comment by FelixBuehler** [comment] 2023-09-19 16:29
@alvar-freude  Then your connection most likely disconnected. At least it sounds like that from what i read.

**Comment by alvar-freude** [comment] 2023-09-19 23:27
> @alvar-freude Then your connection most likely disconnected. At least it sounds like that from what i read.

This is a bit strange, in the admin settings the areas for General Settings etc. were disabled via CSS (CSS class "onlyoffice-hide").
After **saving** the unchanged server settings, everything works normally. It seems that the app internally remembers if an onlyoffice server is connected and this info was reseted during the upgrade. After the upgrade I was not logged in as admin user.

Now everything is fine!
