### ISSUE TITLE
Size of onlyoffice editor embed is scrolling - you can scroll the document editor ribbons out of the screen

### ISSUE THREAD

**Issue by JMoVS** [ONLYOFFICE/onlyoffice-nextcloud#975] opened 2024-04-06 12:17 UTC
Recently, onlyoffice document views are scrolling, even though they shouldn't be.

![grafik](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/assets/7354506/fa48b4fd-a610-4c62-819f-0edb158697b5)

Not sure if this is an issue of nextcloud 28.0.4 or if it's an onlyoffice issue.
It can result in users not being able to see the controls of their documents anymore though:

 
![Bildschirmfoto 2024-04-06 um 14 16 46](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/assets/7354506/c2354d55-da1a-4f3d-91d0-a282e25ebba6)

Can you reproduce this issue?

**Comment by JMoVS** [comment] 2024-04-23 11:27
> This is still a problem in `9.1.2` btw. This problem seems to be specific to the Firefox browser. Chrome is not affected.

it's reproducible for me in Chrome based browsers as well as well as in Safari

**Comment by Petersoj** [comment] 2024-04-23 15:28
> it's reproducible for me in Chrome based browsers as well as well as in Safari

Ah yes you're right. I can reproduce this double scrolling issue in Chrome when I hold the command key while scrolling in an OnlyOffice spreadsheet and hovering over the sidebar. Firefox always double scrolls for me though.
So yeah this seems to be an issue across browsers.

**Comment by JMoVS** [comment] 2024-04-26 07:56
@LinneyS is this reproducible for you as well?

**Comment by SergeyKorneyev** [comment] 2024-04-26 14:16
This should be fixed in version 9.2. Could you check if the update helps?

**Comment by Petersoj** [comment] 2024-04-26 14:37
This issue appears to be resolved in the latest update. Thank you!

**Comment by JMoVS** [comment] 2024-04-27 08:53
> This should be fixed in version 9.2. Could you check if the update helps?

Looks good, will close the issue now

**Closed** 2024-04-27 08:54 UTC
