### ISSUE TITLE
OO not invoked if root of external storage shared via link

### ISSUE THREAD

**Issue by timm2k** [ONLYOFFICE/onlyoffice-nextcloud#35] opened 2018-12-06 10:02 UTC
Dear OnlyOffice Team,

one of our users just figured out that ONLYOFFICE is not invoked if a root folder of an external storage is shared via link. Link users only get a download option instead of opening file in ONLYOFFICE. 

I confirmed this with Nextcloud 13.0.8 + 14.0.4 and nextcloud-onlyoffice 2.1.0.
Document Server is a 5.2.3.

Steps to reproduce:
- add an external storage to your Nextcloud (eg. smb) called "oo"
- create a document.docx in external storage folder "oo"
- share external storage folder "oo" via link (with upload/edit privileges)
- access the link in another tab or webbrowser
- try to open document.docx in ONLYOFFICE :zap: 

I'll expect to open document.docx in ONLYOFFICE and start editing.

Instead of smb I've also checked external storage from other nextcloud shares. Same behavior.

It sill works if subfolders of external storage are shared via link but it doesn't if the root folder is shared.

Regards
Timm

**Comment by LinneyS** [comment] 2018-12-10 16:22
Please specify what authorization do you use when adding external storage?
![cifs](https://user-images.githubusercontent.com/8580527/49745746-b8d1c900-fcb0-11e8-9e46-e6f33640690b.png)

Maybe this issue is a duplicate of ONLYOFFICE/onlyoffice-owncloud#51

**Comment by timm2k** [comment] 2018-12-12 08:00
"Username and Password" is used. If I share a subfolder of an external storage everything is fine. The problem only occurs if I share the root folder of an external storage.

**Comment by LinneyS** [comment] 2018-12-12 12:21
The problem is on the side of Nextcloud. But in 15.0.0 they have already fixed it and everything works.
I'll try to fix it on our side so that it works in Nextcloud 14.0.4 too.

**Comment by timm2k** [comment] 2018-12-13 09:55
Thanks for the update @LinneyS. I can create another issue at Nextcloud on this faulty "VFS" behavior. Since we're paying customers of OO and Nextcloud the fix should be backported to all supported versions ;-)

**Comment by MorrisJobke** [comment] 2019-04-09 12:25
@LinneyS @CarlOnlyoffice @alexanderonlyoffice Mind to close this ticket then? So it's properly identifiable as resolved. Thanks

It seem to be solved in 2356ae2

**Closed** 2019-04-09 12:34 UTC
Labels: bug, external storage
