### ISSUE TITLE
Document server not work with Nextclou

### ISSUE THREAD

**Issue by jeaneduardo** [ONLYOFFICE/onlyoffice-nextcloud#48] opened 2018-12-17 00:47 UTC
Hi,

I already have a server installed with Nextcloud and I installed the onlyoffice document server on a debian 9 server.

Everything is still with the default settings of the installation, browser access the address and I have the following result:
Thank you for choosing ONLYOFFICE!
Document Server is running

When I try to integrate with Nextcloud I enter the URL of the Document Server it just keeps loading and after the following error:
Error attempting to connect (Bad request or time-out error)

Looking at the log in /var/log/onlyoffice/documentserver/nginx.error.log I have the following error:
2018/12/16 21:42:17 [error] 24030 # 24030: * 17 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.40.0.11, server:, request: "POST / ConvertService.ashx HTTP / 1.1 ", upstream:" http://127.0.0.1:8000/ConvertService.ashx ", host:" office.example.com "

In this scenario I have the document server installed on the IP server 10.40.0.3, Nextcloud on the IP server 10.40.0.15 and the Reverse proxy on the server 10.40.0.11
Apache configuration:
<IfModule mod_ssl.c>
    <VirtualHost _default_: 443>
        ServerAdmin admin@example.com
        ServerName office.example.com

        Include /etc/letsencrypt/options-ssl-.conf

        SetEnvIf Host "^ (. *) $" THE_HOST = $ 1
        RequestHeader setifempty X-Forwarded-Proto https
        RequestHeader setifempty X-Forwarded-Host% {THE_HOST} and
        ProxyAddHeaders Off

        ProxyPassMatch (. *) (\ / Websocket) $ "ws: //office.example.lan/$1$2"
        ProxyPass / "http: //office.example.lan/"
        ProxyPassReverse / "http: //office.example.lan/"

        <FilesMatch "\. (Cgi | shtml | phtml | php) $">
                        SSLOptions + StdEnvVars
        </ FilesMatch>
        <Directory / usr / lib / cgi-bin>
                        SSLOptions + StdEnvVars
        </ Directory>
        BrowserMatch "MSIE [2-6]" \
                        nokeepalive ssl-unclean-shutdown \
                        downgrade-1.0 force-response-1.0
        BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown

        ErrorLog /var/log/apache2/office.example.com/error.log
        LogLevel warn
        CustomLog /var/log/apache2/office.example.com/access.log combined
    </ VirtualHost>
</ IfModule>

I tested a different scenario
I placed the Document Server with the valid certificate and removed the reverse proxy, and then I have the following error in /var/log/onlyoffice/documentserver/nginx.error.log.
2018/12/16 22:21:46 [error] 25469 # 25469: * 22 open () "/var/www/onlyoffice/documentserver/sdkjs/common/AllFonts.js" failed (2: No such file or directory) , client: 172.16.170.74, server:, request: "GET /v5.2.4-94//sdkjs/common/AllFonts.js HTTP / 1.1", host: "office.example.com", referrer: "https: / /office.example.com/v5.2.4-94//web-apps/apps/documenteditor/main/index.html?_dc=5.2.4-94&lang=en&customer=ONLYOFFICE&frameEditorId=iframeEditor "

And the web interface is just loading and I get the following error:
The connection is too slow, some of the components could not be loaded. Please reload the page.

I have preference to work in the scenario with reverse proxy.

Regards,

**Comment by Yomark1** [comment] 2019-02-19 13:34
Having the same issue when I updated to the lastest version of the docker and Ubuntu(16.04 to 18.04).
My configuration was working fine(for a long time - updating docker versions and minor ubuntu versions very few weeks).

On the NextCloud site I get: "failed to open stream: HTTP request failed!" errors to ConvertService.ashx. 
I can wget from/to woth servers without issues.

**Comment by alexanderonlyoffice** [comment] 2019-12-26 12:39
@jeaneduardo, @Yomark1, we apologize for the delayed response. Please specify if the issue is still relevant.

**Comment by freumichCH** [comment] 2021-09-17 21:11
@alexanderonlyoffice Can you close this issue? Think its no longer relevant due several updates of the code.

**Comment by ShockwaveNN** [comment] 2021-09-18 10:07
@freumichCH Yeah, thanks for noticing

If this issue is still actual - better to create a new one, original issue was reported in 2018 - it was a long time ago

**Closed by ShockwaveNN** 2021-09-18 10:07 UTC
Labels: needs info
