### ISSUE TITLE
Please implement a dark theme

### ISSUE THREAD

**Issue by Hampusm** [ONLYOFFICE/onlyoffice-nextcloud#264] opened 2020-04-14 09:20 UTC
I beg you. It's too bright. It hurts my eyes.

**Comment by HelenBelova17** [comment] 2020-04-22 12:11
Hello @**Hampusm**, we already thought about this, issue 37457 in our internal issue tracker.

**Comment by ben2ben4042** [comment] 2020-05-12 02:01
> Hello @**Hampusm**, we already thought about this, issue 37457 in our internal issue tracker.
@Rita-Bubnova I see this request has been made in two github requests. I assume the public doesn't have access to the internal bug tracker? If we do, please link it for us so we can track this feature request. Is this on a road map for future release, or too low a priority at this time? Just let us know please. Thanks! Keep up the great work!

**Comment by ShockwaveNN** [comment] 2020-07-21 14:22
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/215

I'll close this issue, since a soon as we implement this feature in DocumentServer I hope it appear in other projects, so better have all discussion in one place

**Closed by ShockwaveNN** 2020-07-21 14:22 UTC
