### ISSUE TITLE
Erro with onlyoffice 5.0

### ISSUE THREAD

**Issue by fabianohugo** [ONLYOFFICE/onlyoffice-nextcloud#354] opened 2020-09-09 22:31 UTC
After updating the onlyofofice package the same stood out strangely. To start start not show the taskbar and ends up showing files just below. Leave an attachment to see.
#

![Screenshot_2020-09-09-19-30-32-686_com miui videoplayer](https://user-images.githubusercontent.com/56777412/92661420-0094e280-f2d3-11ea-8f00-27107dcbdbdc.jpg)

**Comment by ukretschmer** [comment] 2020-09-10 07:25
Duplicate of #350

**Closed** 2020-09-10 13:02 UTC
Labels: duplicate
