### ISSUE TITLE
Cannot edit shared Nextcloud file

### ISSUE THREAD

**Issue by djermann** [ONLYOFFICE/onlyoffice-nextcloud#66] opened 2019-01-30 16:03 UTC
**Do you want to request a *feature* or report a *bug*?**
bug
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. In Nextcloud share a folder readonly with a user.
2. Put a normal file inside this folder and share it again with the same user, but with write permissions.
3. Log-in as the user you shared the folder and file with.

**What is the expected behavior?**
Currently Nextcloud works this way that the file inside the shared file will also appear in the root folder and is editable there but not when opened inside the shared folder, as you can read in this issue from Nextcloud: https://github.com/nextcloud/server/issues/12578

**What is the current behavior?**
Doing this with an ONLYOFFICE file will lead you to be unable to edit this file neither in the root folder or inside the shared folder.
**Did this work in previous versions of DocumentServer?**
probably not
**DocumentServer version:**
5.2.7 CE Docker
**Operating System:**
Debian 9.6

**Comment by LinneyS** [comment] 2019-02-05 07:56
Error at `[0]`
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/v2.1.2/controller/editorcontroller.php#L574
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/v2.1.2/controller/editorcontroller.php#L609

**Comment by rullzer** [comment] 2019-02-18 11:44
In your case you want the file that has READ and EDIT rights. I would write a small function to loop over the array that comes back. And check for those permissions. So you return the node with the most rights you need.

**Comment by LinneyS** [comment] 2019-02-18 12:14
The problem is not only in obtaining rights
Getting a list of objects by file ID leads me to surprise.
Different elements of the list may have different not only rights (`$file->isUpdateable()`), but also names (`$file->getName()`) and location paths (`$file->getParent()->getPath()`).
And it all depends on the webdav path, and not on the identifier

**Comment by rullzer** [comment] 2019-02-18 12:34
yes. This is because a user can rename mountpoints. So if a file is shared to you. You can rename it. Same for a folder.

Of course if a folder is shared to you. And a file inside it. The parent will be different. etc.

**Comment by MorrisJobke** [comment] 2019-04-09 12:25
@LinneyS @CarlOnlyoffice @alexanderonlyoffice  Mind to close this ticket then? So it's properly identifiable as resolved. Thanks

Solved via 7e8dcde

**Closed** 2019-04-09 12:34 UTC
Labels: bug
