### ISSUE TITLE
Issue after upgrade to 4.3.0

### ISSUE THREAD

**Issue by rgl1234** [ONLYOFFICE/onlyoffice-nextcloud#308] opened 2020-07-01 17:11 UTC
After upgrading to onlyoffice 4.3.0 in nextcloud, I get always the following error in nextcloud-log after editing a file in onlyoffice:

OCP\Http\Client\LocalServerException: Host violates local access rules

Because of that error, the modified file is also not changed on the file-location as usual.

How to fix this?

**Comment by HelenBelova17** [comment] 2020-07-02 07:36
Hello @**rgl1234**,

add this line to config.php:
`'allow_local_remote_servers' => true,`

**Comment by rgl1234** [comment] 2020-07-02 08:22
> Hello @**rgl1234**,
> 
> add this line to config.php:
> `'allow_local_remote_servers' => true,`

Thanks Helen, I tried it, but now I get the following error:


Error | PHP | session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209
-- | -- | --

**Comment by LinneyS** [comment] 2020-07-28 12:21
`session_start` - doesn't look like the problem is in ONLYOFFICE
`Host violates local access rules` is fixed with `allow_local_remote_servers`

**Closed by LinneyS** 2020-07-28 12:21 UTC
Labels: configuration
