### ISSUE TITLE
Allow Changing Default Paper size

### ISSUE THREAD

**Issue by wes3161** [ONLYOFFICE/onlyoffice-nextcloud#180] opened 2019-12-17 17:21 UTC
The default paper size is  A4, this is great if your in Europe however in America we have to do things differently so letter is used. It quite annoying to complete a document only to realize it's the wrong paper size and the formatting is wrong. Allowing the default paper size to be changed would significantly help for those in the US, thanks.

**Comment by ShockwaveNN** [comment] 2019-12-18 07:50
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/645

**Comment by LinneyS** [comment] 2019-12-18 15:49
You can change the empty file
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/tree/v4.0.0/assets/en

**Comment by LinneyS** [comment] 2021-05-13 13:37
Hi @wes3161 
You can use templates in the new version.

**Closed by LinneyS** 2021-05-13 13:37 UTC
Labels: enhancement
