### ISSUE TITLE
Nextcloud Snap + OnlyOffice Snap + HAProxy = Bad healthcheck status Error

### ISSUE THREAD

**Issue by moutasem1989** [ONLYOFFICE/onlyoffice-nextcloud#594] opened 2022-02-23 15:04 UTC
Using Snap Store I installed on my home server an instance of NextCloud, OnlyOffice (and other services). HAProxy handles the SSL and is configured with all the services and runs as expected with no errors.

going to `localhost:6699` or `onlyoffice.domain.com` will redirect me to the welcome page of OnlyOffice.
going to `localhost:81` or `nextcloud.domain.com` will redirect me to the front page of NextCloud.
I dont know if this is relevant but my Plex Server is behind `localhost:32400` or `plex.domain.com`.

In NextCloud i have installed [Nextcloud ONLYOFFICE integration app](https://api.onlyoffice.com/editors/nextcloud) and tried to configure it. Sadly giving either one of  `http://localhost:6699/` or `https://onlyoffice.domain.com/` will result in an error regardless if certificate verification is enabled or not:

```
Error | onlyoffice | Exception: Bad healthcheck status

/var/snap/nextcloud/29223/nextcloud/extra-apps/onlyoffice/controller/settingscontroller.php - line 172:OCA\Onlyoffice\DocumentService->checkDocServiceUrl()

/snap/nextcloud/29223/htdocs/lib/private/AppFramework/Http/Dispatcher.php - line 217:OCA\Onlyoffice\Controller\SettingsController->SaveAddress()

/snap/nextcloud/29223/htdocs/lib/private/AppFramework/Http/Dispatcher.php - line 126:OC\AppFramework\Http\Dispatcher->executeController()

/snap/nextcloud/29223/htdocs/lib/private/AppFramework/App.php - line 156:OC\AppFramework\Http\Dispatcher->dispatch()

/snap/nextcloud/29223/htdocs/lib/private/Route/Router.php - line 302:OC\AppFramework\App::main()

/snap/nextcloud/29223/htdocs/lib/base.php - line 1006:OC\Route\Router-match()

/snap/nextcloud/29223/htdocs/index.php - line 36:OC::handleRequest()
```

I have tried adding 'allow_local_remote_servers' => true, to Nextcloud Cofig File .. did dot help.
what steps should i take to debug OnlyOffice to find where the problem is?

**Comment by ShockwaveNN** [comment] 2022-02-24 10:26
Duplicate of https://github.com/ONLYOFFICE/snap-documentserver/issues/91

**Closed by ShockwaveNN** 2022-02-24 10:26 UTC
